export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_RAIDERS = "GET_RAIDERS";
export const GET_FORUMS = "GET_FORUMS";
export const SET_USER_ADMIN_STATUS = "SET_USER_ADMIN_STATUS";
export const GET_SINGLE_FORUM = "GET_SINGLE_FORUM";
